"""Seed data for TS Gate Entry module — exported from demo server (betulbiofuel.mkasystem.com)."""

CUSTOM_DOCPERM = [
	{"parent": "Company", "role": "Accounts Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Company", "role": "Accounts User", "read": 1, "print": 1, "email": 1},
	{"parent": "Company", "role": "Auditor"},
	{"parent": "Company", "role": "department user", "read": 1, "export": 1},
	{"parent": "Company", "role": "Employee", "read": 1},
	{"parent": "Company", "role": "Projects User", "read": 1},
	{"parent": "Company", "role": "Purchase Manager", "read": 1, "export": 1},
	{"parent": "Company", "role": "Purchase User", "read": 1},
	{"parent": "Company", "role": "Sales User", "read": 1},
	{"parent": "Company", "role": "Stock User", "read": 1},
	{"parent": "Company", "role": "Stores User", "read": 1, "export": 1},
	{"parent": "Company", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Cost Center", "role": "Accounts Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Cost Center", "role": "Accounts User", "read": 1, "report": 1, "print": 1, "email": 1},
	{"parent": "Cost Center", "role": "Auditor", "read": 1, "report": 1, "export": 1},
	{"parent": "Cost Center", "role": "Employee", "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Cost Center", "role": "Purchase Manager", "read": 1, "write": 1, "create": 1, "export": 1},
	{"parent": "Cost Center", "role": "Purchase User", "read": 1},
	{"parent": "Cost Center", "role": "Quality Inspector", "read": 1, "export": 1},
	{"parent": "Cost Center", "role": "Sales User", "read": 1},
	{"parent": "Cost Center", "role": "Stock User", "read": 1, "export": 1},
	{"parent": "Currency", "role": "Accounts Manager", "read": 1, "export": 1},
	{"parent": "Currency", "role": "Accounts User", "read": 1, "export": 1},
	{"parent": "Currency", "role": "department user", "read": 1, "export": 1},
	{"parent": "Currency", "role": "Purchase User", "read": 1, "export": 1},
	{"parent": "Currency", "role": "Sales User", "read": 1, "export": 1},
	{"parent": "Currency", "role": "Stock User", "read": 1, "export": 1},
	{"parent": "Currency", "role": "Stores User", "read": 1, "export": 1},
	{"parent": "Currency", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "export": 1},
	{"parent": "Item", "role": "Accounts Manager", "read": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Item", "role": "Accounts User", "read": 1},
	{"parent": "Item", "role": "CTO", "read": 1},
	{"parent": "Item", "role": "Desk User", "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Item", "role": "G1 Security", "read": 1},
	{"parent": "Item", "role": "G2 Gate Operator", "read": 1},
	{"parent": "Item", "role": "Item Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Item", "role": "Maintenance User", "read": 1},
	{"parent": "Item", "role": "Manufacturing User", "read": 1},
	{"parent": "Item", "role": "Purchase Manager", "read": 1, "create": 1, "export": 1},
	{"parent": "Item", "role": "Purchase User", "read": 1},
	{"parent": "Item", "role": "Sales User", "read": 1},
	{"parent": "Item", "role": "Stock Manager", "read": 1, "write": 1, "create": 1, "report": 1, "print": 1, "email": 1},
	{"parent": "Item", "role": "Stock User", "read": 1, "write": 1, "create": 1, "report": 1, "print": 1, "email": 1},
	{"parent": "Item", "role": "Stores User", "read": 1},
	{"parent": "Item", "role": "Weighbridge Operator", "read": 1},
	{"parent": "Material Request", "role": "AVP", "read": 1, "write": 1, "delete": 1, "submit": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "CEO", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "Department Head", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "General Manager", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "HR Manager", "read": 1, "create": 1, "export": 1},
	{"parent": "Material Request", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "MD", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "Purchase Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "Purchase User", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "Quality Inspector", "read": 1, "write": 1, "create": 1, "submit": 1, "export": 1},
	{"parent": "Material Request", "role": "Stock Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "Stock User", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Material Request", "role": "Stores User", "read": 1, "export": 1},
	{"parent": "Purchase Order", "role": "Accounts Manager", "read": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "AVP", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "CEO", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "CTO", "read": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "Department Head", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "G1 Security", "read": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "G2 Gate Operator", "read": 1},
	{"parent": "Purchase Order", "role": "General Manager", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "Grain Purchase Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "MD", "read": 1, "write": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "Purchase Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "Purchase User", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "Stock User", "read": 1, "report": 1},
	{"parent": "Purchase Order", "role": "Stores User", "read": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "Weighbridge Operator", "read": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Order", "role": "Purchase Manager", "permlevel": 1, "read": 1, "write": 1},
	{"parent": "Purchase Receipt", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Invoice", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Receipt", "role": "Accounts Manager", "read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1, "amend": 1, "export": 1},
	{"parent": "Purchase Receipt", "role": "Accounts User", "read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1, "report": 1},
	{"parent": "Purchase Receipt", "role": "Purchase User", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Receipt", "role": "Stock Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Receipt", "role": "Stock User", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Purchase Receipt", "role": "Stores User", "read": 1, "write": 1, "create": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Approval Limit", "role": "CEO", "read": 1},
	{"parent": "TS Approval Limit", "role": "General Manager", "read": 1},
	{"parent": "TS Approval Limit", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Approval Limit", "role": "MD", "read": 1},
	{"parent": "TS Approval Limit", "role": "Purchase Manager", "read": 1, "write": 1, "create": 1, "export": 1, "email": 1},
	{"parent": "TS Approval Limit", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1},
	{"parent": "TS Item Code Settings", "role": "CTO", "read": 1, "write": 1},
	{"parent": "TS Item Code Settings", "role": "Stock User", "read": 1, "write": 1, "create": 1, "export": 1},
	{"parent": "TS Item Code Settings", "role": "System Manager", "read": 1, "write": 1, "create": 1},
	{"parent": "TS Item Creator", "role": "CTO", "read": 1, "write": 1, "create": 1, "report": 1},
	{"parent": "TS Item Creator", "role": "Manufacturing User", "read": 1, "write": 1, "create": 1, "export": 1},
	{"parent": "TS Item Creator", "role": "Purchase Master Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "export": 1},
	{"parent": "TS Item Creator", "role": "Stock User", "read": 1, "write": 1, "create": 1, "report": 1, "export": 1},
	{"parent": "TS Item Creator", "role": "Stores User", "read": 1, "write": 1, "create": 1},
	{"parent": "TS Item Creator", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1},
	{"parent": "TS MR Approval Route", "role": "AVP", "read": 1},
	{"parent": "TS MR Approval Route", "role": "CEO", "read": 1},
	{"parent": "TS MR Approval Route", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS MR Approval Route", "role": "Purchase Manager", "read": 1, "write": 1, "create": 1, "export": 1, "email": 1},
	{"parent": "TS MR Approval Route", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1},
	{"parent": "TS PO Approval Rule", "role": "CEO", "read": 1},
	{"parent": "TS PO Approval Rule", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS PO Approval Rule", "role": "MD", "read": 1},
	{"parent": "TS PO Approval Rule", "role": "Purchase Manager", "read": 1, "write": 1, "create": 1, "export": 1, "email": 1},
	{"parent": "TS PO Approval Rule", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1},
	{"parent": "TS Budget Proposal", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS CC Approval Config", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Deduction Sheet", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Driver Master", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Gate Entry", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "submit": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Gate Pass Destination", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Item Code Settings", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Item Creator", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Location", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Material Inspection", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Purchase Category", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Quality Inspection", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Quality Inspection", "role": "Quality Inspector", "read": 1, "write": 1, "create": 1, "report": 1, "export": 1},
	{"parent": "TS Quality Inspection", "role": "Stores User", "read": 1, "write": 1, "create": 1},
	{"parent": "TS Quality Inspection", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1},
	{"parent": "TS Quality Inspection", "role": "G1 Security", "read": 1},
	{"parent": "TS Quality Inspection", "role": "G2 Gate Operator", "read": 1},
	{"parent": "TS Quality Inspection", "role": "Weighbridge Operator", "read": 1},
	{"parent": "TS Quality Inspection", "role": "Accounts Manager", "read": 1},
	{"parent": "TS Settings", "role": "IT Head", "read": 1, "write": 1, "create": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Token", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "cancel": 1, "amend": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Supplier", "role": "Accounts Manager", "read": 1, "write": 1, "create": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Transport Master", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Transporter Vehicle", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Variant", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Vehicle Master", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Visitor", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Visiting Company", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Weighbridge Log", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Token", "role": "Accounts Manager", "read": 1},
	{"parent": "TS Token", "role": "Admin Reception", "read": 1, "write": 1, "create": 1, "export": 1},
	{"parent": "TS Token", "role": "CTO", "read": 1, "write": 1},
	{"parent": "TS Token", "role": "G1 Security", "read": 1, "write": 1, "create": 1},
	{"parent": "TS Token", "role": "G2 Gate Operator", "read": 1, "write": 1, "create": 1, "print": 1},
	{"parent": "TS Token", "role": "Quality Inspector", "read": 1},
	{"parent": "TS Token", "role": "Stores User", "read": 1, "report": 1, "print": 1},
	{"parent": "TS Token", "role": "System Manager", "read": 1, "write": 1, "create": 1},
	{"parent": "TS Token", "role": "Weighbridge Operator", "read": 1},
	{"parent": "TS Token", "role": "CTO", "permlevel": 1, "read": 1},
	{"parent": "TS Token", "role": "G1 Security", "permlevel": 1, "read": 1, "write": 1},
	{"parent": "TS Token", "role": "System Manager", "permlevel": 1, "read": 1, "write": 1},
	{"parent": "TS Transport Master", "role": "Accounts Manager", "read": 1, "write": 1, "create": 1, "delete": 1},
	{"parent": "TS Transport Master", "role": "G1 Security", "read": 1, "write": 1, "create": 1, "export": 1},
	{"parent": "TS Transport Master", "role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1},
	{"parent": "TS Unloading Entry", "role": "Accounts Manager", "read": 1},
	{"parent": "TS Unloading Entry", "role": "IT Head", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "TS Unloading Entry", "role": "Quality Inspector", "read": 1, "export": 1},
	{"parent": "TS Unloading Entry", "role": "Quality Manager", "read": 1, "export": 1},
	{"parent": "TS Unloading Entry", "role": "Stores User", "read": 1, "write": 1, "create": 1},
	{"parent": "TS Unloading Entry", "role": "System Manager", "read": 1, "write": 1, "create": 1},
	{"parent": "TS Unloading Entry", "role": "Weighbridge Operator", "read": 1},
	{"parent": "Warehouse", "role": "Accounts Manager", "read": 1},
	{"parent": "Warehouse", "role": "Accounts User", "read": 1, "report": 1, "print": 1, "email": 1},
	{"parent": "Warehouse", "role": "CTO", "read": 1},
	{"parent": "Warehouse", "role": "G1 Security", "read": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Warehouse", "role": "G2 Gate Operator", "read": 1},
	{"parent": "Warehouse", "role": "Item Manager", "read": 1, "write": 1, "create": 1, "delete": 1, "report": 1, "export": 1, "share": 1, "print": 1, "email": 1},
	{"parent": "Warehouse", "role": "Manufacturing User", "read": 1},
	{"parent": "Warehouse", "role": "Purchase Manager", "read": 1, "export": 1},
	{"parent": "Warehouse", "role": "Purchase User", "read": 1, "report": 1, "print": 1, "email": 1},
	{"parent": "Warehouse", "role": "Sales User", "read": 1, "report": 1, "print": 1, "email": 1},
	{"parent": "Warehouse", "role": "Stock User", "read": 1, "report": 1, "print": 1, "email": 1},
	{"parent": "Warehouse", "role": "Stores User", "read": 1},
	{"parent": "Warehouse", "role": "Weighbridge Operator", "read": 1},
]

PROPERTY_SETTERS = [
	{"doc_type": "Material Request", "field_name": "ts_mr_status", "property": "columns", "property_type": "Int", "value": "2", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "ts_mr_status", "property": "fieldtype", "property_type": "Select", "value": "Select", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "ts_mr_status", "property": "in_list_view", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "ts_mr_status", "property": "in_standard_filter", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "ts_mr_status", "property": "label", "property_type": "Data", "value": "Approval Status", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "ts_mr_status", "property": "options", "property_type": "Text", "value": "Not Submitted\nPending Dept. User\nPending Dept. Head\nPending AVP\nPending CEO\nPending GM\nApproved\nRevised\nRejected\nOn Hold", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "buying_price_list", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "material_request_type", "property": "options", "property_type": "Text", "value": "Purchase\nMaterial Transfer\nMaterial Issue\nManufacture\nCustomer Provided\nService Request", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "schedule_date", "property": "in_list_view", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request", "field_name": "title", "property": "in_list_view", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request Item", "field_name": "actual_qty", "property": "columns", "property_type": "Data", "value": "2", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request Item", "field_name": "actual_qty", "property": "in_list_view", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request Item", "field_name": "actual_qty", "property": "label", "property_type": "Data", "value": "Available Qty", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request Item", "field_name": "item_code", "property": "columns", "property_type": "Int", "value": "2", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request Item", "field_name": "schedule_date", "property": "in_list_view", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Material Request Item", "field_name": "warehouse", "property": "columns", "property_type": "Int", "value": "2", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "ts_approval_status", "property": "columns", "property_type": "Int", "value": "2", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "ts_approval_status", "property": "fieldtype", "property_type": "Select", "value": "Select", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "ts_approval_status", "property": "in_list_view", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "ts_approval_status", "property": "in_standard_filter", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "ts_approval_status", "property": "label", "property_type": "Data", "value": "Approval Status", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "ts_approval_status", "property": "options", "property_type": "Text", "value": "Not Submitted\nPending PM\nPending Grain PM\nPending Dept. Head\nPending CEO\nPending MD\nPending GM\nApproved\nRevised\nRejected", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "rounded_total", "property": "hidden", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order", "field_name": "in_words", "property": "hidden", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order Item", "field_name": "schedule_date", "property": "in_list_view", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order Item", "field_name": "warehouse", "property": "in_list_view", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Order Item", "field_name": "warehouse", "property": "columns", "property_type": "Int", "value": "2", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt Item", "field_name": "barcode", "property": "hidden", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt Item", "field_name": "from_warehouse", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Invoice Item", "field_name": "from_warehouse", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt", "field_name": "lr_date", "property": "label", "property_type": "Data", "value": "Transport Receipt Date", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt", "field_name": "lr_no", "property": "label", "property_type": "Data", "value": "Transport Receipt No", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt", "field_name": "rounded_total", "property": "hidden", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt", "field_name": "in_words", "property": "hidden", "property_type": "Check", "value": "0", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt", "field_name": "transporter_name", "property": "fetch_from", "property_type": "Small Text", "value": "transporter.supplier_name", "doctype_or_field": "DocField"},
	{"doc_type": "Purchase Receipt", "field_name": "transporter_name", "property": "fieldtype", "property_type": "Select", "value": "Small Text", "doctype_or_field": "DocField"},
	{"doc_type": "TS Deduction Sheet", "field_name": "naming_series", "property": "default", "property_type": "Text", "value": "BBPL-DED-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Deduction Sheet", "field_name": "naming_series", "property": "options", "property_type": "Text", "value": "BBPL-DED-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Gate Entry", "field_name": "driver", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "TS Gate Entry", "field_name": "driver_mobile", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "TS Gate Entry", "field_name": "driver_name", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "TS Gate Entry", "field_name": "naming_series", "property": "default", "property_type": "Text", "value": "BBPL-GE-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Gate Entry", "field_name": "naming_series", "property": "options", "property_type": "Text", "value": "BBPL-GE-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Gate Entry", "field_name": "vehicle_master", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "TS Gate Entry", "field_name": "vehicle_type", "property": "hidden", "property_type": "Check", "value": "1", "doctype_or_field": "DocField"},
	{"doc_type": "TS Quality Inspection", "field_name": "naming_series", "property": "default", "property_type": "Text", "value": "BBPL-QI-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Quality Inspection", "field_name": "naming_series", "property": "options", "property_type": "Text", "value": "BBPL-QI-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Unloading Entry", "field_name": "naming_series", "property": "default", "property_type": "Text", "value": "BBPL-UL-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Unloading Entry", "field_name": "naming_series", "property": "options", "property_type": "Text", "value": "BBPL-UL-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Weighbridge Log", "field_name": "naming_series", "property": "default", "property_type": "Text", "value": "BBPL-WB-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "TS Weighbridge Log", "field_name": "naming_series", "property": "options", "property_type": "Text", "value": "BBPL-WB-.YYYY.-.#####", "doctype_or_field": "DocField"},
	{"doc_type": "Supplier", "field_name": "supplier_type", "property": "options", "property_type": "Text", "value": "Company\nIndividual\nPartnership\nHUF\nFirm\nPerson\nArtificial & Judicial Person", "doctype_or_field": "DocField"},
	{"doc_type": "Customer", "field_name": "customer_type", "property": "options", "property_type": "Text", "value": "Company\nIndividual\nPartnership\nHUF\nFirm\nPerson\nArtificial & Judicial Person", "doctype_or_field": "DocField"},
]
